import withAuthentication from "@/components/hoc/withAuthentication";
import Header from "@/components/shared/Header";
import LogoutButton from "@/components/shared/LogoutButton";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

const User = ({ currentUser }) => {
  return (<>
    <Head>
      <title>FELE User</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={inter.className + " h-full w-full"}>
      <article className="">
        <Header />
      </article>
      <LogoutButton />
    </main>
  </>)
}

export default withAuthentication(User);