import withAuthentication from "@/components/hoc/withAuthentication";
import LogoutButton from "@/components/shared/LogoutButton";
import Sidebar from "@/components/shared/Sidebar";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

const User = ({ currentUser }) => {
  return (<>
    <Head>
      <title>FELE User</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={inter.className + " h-full w-full grid grid-cols-10"}>
      <Sidebar />
      <main className="col-span-8">
        This is user page
        {/* TODO: Add the user functions here */}
      </main>
      <LogoutButton />
    </div>
  </>)
}

export default withAuthentication(User);