import Head from "next/head";
import { Inter } from 'next/font/google';
import withAuthentication from "@/components/withAuthentication";

const inter = Inter({ subsets: ['latin'] })

const Admin = () => {
  const renderDashboard = () => {
    return (
      <section>Admin Dashboard</section>
    )
  }

  return (<>
    <Head>
      <title>FELE Client App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={inter.className}>
      <article className="h-full w-full flex justify-center items-center">
        {renderDashboard()}
      </article>
    </main>
  </>)
}

export default withAuthentication(Admin);