import Head from "next/head";
import { Inter } from 'next/font/google';
import { useContext, useEffect, useState } from "react";
import { AppContext } from "../_app";
import Router from "next/router";

const inter = Inter({ subsets: ['latin'] })

export default function Admin() {
  const [isLoading, setIsLoading] = useState(true);
  const { context } = useContext(AppContext);

  useEffect(() => {
    if (!context.network || !context.channel) {
      Router.push("/");
    } else {
      setIsLoading(false)
    }
  }, [context])

  const renderDashboard = () => {
    if (isLoading) return <div>Loading</div>
    return (
      <section>Admin Dashboard</section>
    )
  }

  return (<>
    <Head>
      <title>FELE Client App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={inter.className}>
      <article className="h-full w-full flex justify-center items-center">
        {renderDashboard()}
      </article>
    </main>
  </>)
}